# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='destination',
            field=models.CharField(default='Bradley International Airport', max_length=128),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
