# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_auto_20170314_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pickup',
            field=models.CharField(default='Phelps Gate', max_length=128),
        ),
    ]
