# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_auto_20170410_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='num_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='current_people',
        ),
        migrations.AddField(
            model_name='appointment',
            name='current_people',
            field=models.ManyToManyField(related_name='apps_guest', to=settings.AUTH_USER_MODEL),
        ),
    ]
