# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_auto_20170423_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='creator',
        ),
    ]
