# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_remove_riderequest_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='status',
            field=models.CharField(default='pending', max_length=64),
        ),
    ]
